<?php

namespace BlogBundle\Repository;

/**
 * album_pictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class album_pictureRepository extends \Doctrine\ORM\EntityRepository
{
    public function listPicture($userId,$category)
    {
        $req = $this->createQueryBuilder('a');
        $req
            ->where('a.user ='.$userId)
            ->andWhere("a.category = '".$category."'");

        return $req
            ->getQuery()
            ->getResult()
            ;
    }
}
